# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 531fb3811555c176ba594711a025e1d4ac9280589cf443eb04aec869b60324fc07d3f1a782ef031a539e1b9b9248399e3bca911c44ca09e549011bec368f4d90

test:
  secret_key_base: 93f005343834a0eb4990b5519e1fc1af7ec171f86a54b6c47c93519759137237717bd9a4690d9fa96c8d7cb3761599e87827d41f19d0aacf6b479ac1f7554a62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
